## Question 1

Approach: Because the problem is asking for the distinct overlapping values, this hits towards using some sort of set function. Looking through the numpy documentation to find a similar command gives us the intersect1d command.

In [2]:
#import numpy
import numpy as np

#make arrays a and b from the directions
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])


#numpy has an intersect command in the documentation that will find the distinct overlapping values of the sets
c = np.intersect1d(a,b)
c

array([2, 4])

## Question 2

Approach: The question ia asking for an array of consecutive intergers that go down the rows instead of across the columns. This suggests using the transpose command. I created an consecutive array of integers with the arange command and took the transpose to solve this problem.

In [8]:
#create array called arr with integers from 1-15 and reshape into a 5x3 array
arr = np.arange(1,16).reshape(3,5)

#transpose this array to make a 3x5 array in the desired order
arr.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

## Question 3

Approach: Similarly to problem 1, I found the intersection of arrays a and b using the intersect1d command. After finding these values, I removed them from array a. I wanted to iterate through each of the elements in c but had some trouble with producing that code. Given that difficulty, the code below still completes the task. 

In [36]:
#create arrays for this problem
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

#Fins intersection values
c = np.intersect1d(a,b)

#remove intersection values from array a
d = a[(a != 3)&(a != 5)&(a != 12)]
d


[ 3  5 12]


array([ 7, 15,  1,  8])

## Question 4

Approach: The first step of this problem is to create an array of cummulative values of the miles traveled. Because the problem stated "by hand", I manually entered 35 values (with 4 days of rest) to add up to the miles from NYC to Key West. The second step is to find the difference. I did this by duplicating the cummulative array and adding the value 0 to it. From here I can now subtract the elements of the array (while ensureing they are the same length) to find the distance traveled each day. Lastly, I created a function to print this difference along with the day of the trip.

In [28]:
#for reference, there are 1519 miles from NYC to Key West via bike

#the cummulative array are the values that you recorded "by hand"
#enter values for 35 days and then add 4 days of breaks until the sum is 1519 miles to replicate this
cummulative = np.array([35, 120, 146, 195, 225,
                        268, 301, 345, 386, 410, 
                        410, 445, 496, 525, 578, 
                        604, 665, 714, 786, 825, 
                        825, 867, 915, 1001, 1115, 
                        1115, 1192, 1235, 1300, 1376, 
                        1376, 1415, 1450, 1486, 1519])

#create another array with the values 0 inserted as the first value
cummulative_extend = np.insert(cummulative, 0, 0)

#create array 'miles' by subtracting the first 35  values of
#cummulative_ extended array from the original cummulative array to give the difference
miles = cummulative[:35] - cummulative_extend[:35]

#define function to print the miles traveled each day with the day number
def miles_per_day(n):
    for i in miles:
        n = n + 1
        print('I rode ', i, ' miles on day ', n)
        
#use function above starting from the first day
miles_per_day(0)


I rode  35  miles on day  1
I rode  85  miles on day  2
I rode  26  miles on day  3
I rode  49  miles on day  4
I rode  30  miles on day  5
I rode  43  miles on day  6
I rode  33  miles on day  7
I rode  44  miles on day  8
I rode  41  miles on day  9
I rode  24  miles on day  10
I rode  0  miles on day  11
I rode  35  miles on day  12
I rode  51  miles on day  13
I rode  29  miles on day  14
I rode  53  miles on day  15
I rode  26  miles on day  16
I rode  61  miles on day  17
I rode  49  miles on day  18
I rode  72  miles on day  19
I rode  39  miles on day  20
I rode  0  miles on day  21
I rode  42  miles on day  22
I rode  48  miles on day  23
I rode  86  miles on day  24
I rode  114  miles on day  25
I rode  0  miles on day  26
I rode  77  miles on day  27
I rode  43  miles on day  28
I rode  65  miles on day  29
I rode  76  miles on day  30
I rode  0  miles on day  31
I rode  39  miles on day  32
I rode  35  miles on day  33
I rode  36  miles on day  34
I rode  33  miles on day  

## Question 5

In [32]:
#this is the given code from the problem
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').values

# verify you have an ndarray object
type(nyc_water)

numpy.ndarray

Appraoch: First, I made 1 dimensional arrays to represent each column of the table. From here I could easily use numpy commands from the documentation to find the information required to answer each part of this problem.

In [66]:
#create array for year
year = nyc_water[:,0]

#create array for nyc population
new_york_city_population = nyc_water[:,1]

#create array for consumption in millions of gallons per day
nyc_consumption_million_gallons_per_day = nyc_water[:,2]

#create array for per capita daily water consumption
per_capita_gallons_per_person_per_day = nyc_water[:,3]


#PART A
#find max of consumption array
a = np.max(nyc_consumption_million_gallons_per_day)

print( a, ' is the maximum NYC water concumption in millions of gallons per day.')


#PART B - 40 years since computer start counting from 0
#find length of the year array
b = len(year)
print(b, ' is the number of calendar years in this data set.')

#PART C
#find the mean and std of per_capita_gallons_per_person_per_day array using numpy functions
c1 = np.mean(per_capita_gallons_per_person_per_day)
c2 = np.std(per_capita_gallons_per_person_per_day)

print(c1, ' is the mean per capita daily water consumption.') 
print(c2, ' is the standard deviation of the per capita daily water consumption.')

#PART D
#find the difference of array values of the population array using numpy's diff command
pop_diff = np.diff(new_york_city_population)

print('The array of population difference is ', pop_diff)

1512.0  is the maximum NYC water concumption in millions of gallons per day.
39  is the number of calendar years in this data set.
160.30769230769232  is the mean per capita daily water consumption.
31.51894330370624  is the standard deviation of the per capita daily water consumption.
The array of population difference is  [-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]


In [48]:
nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1